In [4]:
import torch as th

In [19]:
# Scalar
t1 = th.tensor(1.)
t1

tensor(1.)

In [20]:
# Vector
t2 = th.tensor([1., 2., 3., 4])
t2

tensor([1., 2., 3., 4.])

In [21]:
# Matrix
t3 = th.tensor([[1, 2.], [3, 4], [5, 6]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [26]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])


In [48]:
x = th.tensor([[1, 2], [3., 4], [5, 6]])
w = th.tensor([[7, 8, 9], [10, 11., 12]], requires_grad=True)
b = th.tensor([1, 2., 3], requires_grad=True)

In [49]:
y = x * w + b
y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [41]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [35]:
print(x.grad)
print(w.grad)
print(b.grad)
print(y.grad_fn)

None
tensor(3.)
tensor(1.)


In [36]:
import numpy as np

In [37]:
x = np.array([1, 2., 3])

In [38]:
y = th.from_numpy(x)
y

tensor([1., 2., 3.], dtype=torch.float64)